### PR TITLE
Restructure imports via goimports

### PR DESCRIPTION
**Pull request by mbeacom**

### CODE REVIEW

**Comment by winlinvip** [comment]
Did you use some cmd tool to format the code? And what's the cmd?

**Comment by mbeacom** [comment]
I'm using [Atom](https://atom.io/) as my editor with [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports) and [gofmt](https://golang.org/cmd/gofmt/) which are leveraged by the [Go-imports Atom package](https://atom.io/packages/go-imports)

`go get -v golang.org/x/tools/cmd/goimports`

**Comment by winlinvip** [comment]
I got it. I know gofmt, but not goimports yet, I will study it then merge your pr, thanks.

**Comment by mbeacom** [comment]
Any time to look at goimports yet? @winlinvip

**Comment by winlinvip** [comment]
I don't think it's very important to use goimports or just gofmt, because I need to refine the basic structure for oryx to make the infrastructure more strong. But I am not sure about the arch of oryx and lack of time, so please hold on, don't close this PR for it's useful(only not hurry to merge it).

**Comment by mbeacom** [comment]
@winlinvip Thank you!  That sounds good to me.  If you need anything, let me know.  I'd really like to contribute where and when possible!

**Comment by winlinvip** [comment]
@mbeacom Please help to review the introduction of oryx, I have known the new arch of oryx. 
https://github.com/ossrs/go-oryx#go-oryx

**Comment by mbeacom** [comment]
@winlinvip I sent you a Skype message with some questions and some changes to the readme.  Let me know if you need anything else!  I'll close this for now.

**Comment by winlinvip** [comment]
@mbeacom 👌

**Pull request closed without merging**
